# Generated by Django 3.2.9 on 2021-12-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplestrangle', '0002_auto_20211209_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='EntryDateTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='Exit',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='ExitDateTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='PL',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
