# Generated by Django 3.2.9 on 2021-12-02 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=3)),
                ('Entry', models.FloatField()),
                ('Exit', models.FloatField()),
                ('PL', models.FloatField()),
                ('EntryDateTime', models.DateTimeField()),
                ('ExitDateTime', models.DateTimeField()),
            ],
        ),
    ]
